In [1]:
%config InlineBackend.figure_format = 'retina'

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
from matplotlib import pyplot as plt
from matplotlib import rcParams

In [3]:
# We need to do it in a separate cell. See:
# https://github.com/jupyter/notebook/issues/3385
plt.style.use('default')
rcParams.update({'font.size':12})

In [4]:
top = Path("lecture-05")

In [5]:
top.mkdir(exist_ok=True)

``FileExistsError`` will be raised if you do

```python
top.mkdir()
```

# Format String

Make format string by ``f""`` or ``"".format()``

In [6]:
prefix = "test"
for i in range(3):
    fpath = top/f"{prefix}_{i}.txt"
    fpath.touch()
    print(fpath)

lecture-05/test_0.txt
lecture-05/test_1.txt
lecture-05/test_2.txt


In [7]:
for i in range(3):
    fpath = top/"{x:s}_{y:d}.txt".format(x=prefix, y=i)
#   Identical to
#     fpath = top/"{x}_{y}.txt".format(x=prefix, y=i)
    fpath.touch()
    print(fpath)

lecture-05/test_0.txt
lecture-05/test_1.txt
lecture-05/test_2.txt


In [8]:
for i in range(3):
    fpath = top/"{1}_{0}.txt".format(i, prefix)
#   Identical to
#     fpath = top/"{0}_{1}.txt".format(prefix, i)
    fpath.touch()
    print(fpath)

lecture-05/test_0.txt
lecture-05/test_1.txt
lecture-05/test_2.txt


In [9]:
for i in range(3):
    fpath = top/"{}_{}.txt".format(prefix, i)
    fpath.touch()
    print(fpath)

lecture-05/test_0.txt
lecture-05/test_1.txt
lecture-05/test_2.txt


Although a bit deprecated by now, ``%`` is also used:

In [10]:
for i in range(3):
    fpath = top/("%s_%s.txt" % (prefix, i))
    fpath.touch()
    print(fpath)

lecture-05/test_0.txt
lecture-05/test_1.txt
lecture-05/test_2.txt


Some summary [here](https://pyformat.info/)

In [11]:
fmts = {"Default" : "{}",
        "Precision" : "{:.1f}",
        "Sign" : "{:+.1f}",
        "Fixed length" : "{:10.1f}",
        "Fixed length, left" : "{:<10.1f}",
        "Fixed length, center" : "{:^10.1f}",
        "Fixed length, fill" : "{:ㅋ^10.1f}",
        "Leading zeros (application of Fixed length)" : "{:0>10.0f}",
        "Sign with space": "{:=+15f}",
        "exponent" : "{:e}",
        "shorter" : "{:g}",
       }

values = [1234567, 1234.567, 1.234567890, -10]

for s, f in fmts.items():
    print(s, f)
    for v in values:
        print(f.format(v))
    print()

Default {}
1234567
1234.567
1.23456789
-10

Precision {:.1f}
1234567.0
1234.6
1.2
-10.0

Sign {:+.1f}
+1234567.0
+1234.6
+1.2
-10.0

Fixed length {:10.1f}
 1234567.0
    1234.6
       1.2
     -10.0

Fixed length, left {:<10.1f}
1234567.0 
1234.6    
1.2       
-10.0     

Fixed length, center {:^10.1f}
1234567.0 
  1234.6  
   1.2    
  -10.0   

Fixed length, fill {:ㅋ^10.1f}
1234567.0ㅋ
ㅋㅋ1234.6ㅋㅋ
ㅋㅋㅋ1.2ㅋㅋㅋㅋ
ㅋㅋ-10.0ㅋㅋㅋ

Leading zeros (application of Fixed length) {:0>10.0f}
0001234567
0000001235
0000000001
0000000-10

Sign with space {:=+15f}
+1234567.000000
+   1234.567000
+      1.234568
-     10.000000

exponent {:e}
1.234567e+06
1.234567e+03
1.234568e+00
-1.000000e+01

shorter {:g}
1.23457e+06
1234.57
1.23457
-10



## 2. Try-Except-Finally

In [12]:
try:
    print("trying")
    top.mkdir()
except FileExistsError:
    print("exception happened")
    top.mkdir(exist_ok=True)
finally:
    print("Done")

trying
exception happened
Done


Compare with this:

In [13]:
if top.exists():
    top.mkdir(exist_ok=True)
else:
    top.mkdir()

A slightly meaningful way of using it:

In [14]:
def dividing(x, y):
    try:
        return x/y
    except ZeroDivisionError:
        return np.inf
    finally:
        print("This is 'finally'")
        return 1

print(dividing(0, 1))
print(dividing(1, 0))

This is 'finally'
1
This is 'finally'
1


In [15]:
dict4df = {}
for i in range(50):
    quotient = i//5
    remainder = i%5
    try:
        dict4df[remainder].append(i)
    except KeyError:
        dict4df[remainder] = [i]

In [16]:
dict4df

{0: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45],
 1: [1, 6, 11, 16, 21, 26, 31, 36, 41, 46],
 2: [2, 7, 12, 17, 22, 27, 32, 37, 42, 47],
 3: [3, 8, 13, 18, 23, 28, 33, 38, 43, 48],
 4: [4, 9, 14, 19, 24, 29, 34, 39, 44, 49]}

In [17]:
df = pd.DataFrame.from_dict(dict4df)    
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

## ``isinstance``

In [18]:
def str2list(s):
    if isinstance(s, str):
        return [s]
    elif isinstance(s, list):
        print("Already list...")
        return s
    else:
        raise TypeError(f"s must be either str or list. It's now {s}, which is type {type(s)}.")

In [19]:
str2list("a")

['a']

In [20]:
str2list(['a'])

Already list...


['a']

In [21]:
str2list(1)

TypeError: s must be either str or list. It's now 1, which is type <class 'int'>.

## ``atleast_1d``

In [22]:
def squaring(a):
    if not isinstance(a, (int, float, list, tuple, np.ndarray)):
        print(f"Is the type of a as you expect? It's now {type(a)}")
    _a = np.atleast_1d(a)
    return _a**2

In [23]:
squaring(10)

array([100])

In [24]:
squaring([10, 100])

array([  100, 10000])

In [25]:
squaring((3, 5))

array([ 9, 25])

In [26]:
squaring(np.arange(10).reshape(2, 5))

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [27]:
squaring("1")

Is the type of a as you expect? It's now <class 'str'>


TypeError: ufunc 'square' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''